### PR TITLE
Add Grok support

### PR DESCRIPTION
**Pull request by sgarg26**
Added support for X's Grok. Currently, this only supports textual content, but I am working on adding support for image reasoning. 

Also fixed a small error in `examples/basic_example.py` to use the renamed `easilyai.EasilyAIPipeline()` instead of `easilyai.EasyAIPipeline()`

### CODE REVIEW

**Comment by GustyCube** [comment]
Hey @sgarg26! Thanks for this! I've modified one thing so the model isn't explicitly defined in the request, rather it should use "self.model". I will merge it.

Also, thanks for noticing the issue with easyai.

**Comment by sgarg26** [comment]
Yep, you're right, thanks for catching that.

**Comment by GustyCube** [comment]
@sgarg26 will you be doing image generation as well?

**Comment by GustyCube** [comment]
@sgarg26

**Pull request merged**
